[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn api.base:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Deploy the web service
[services.web]
name = "seo-agent-api"
envVars = [
  { key = "OPENAI_API_KEY", value = "${{OPENAI_API_KEY}}" },
  { key = "ANTHROPIC_API_KEY", value = "${{ANTHROPIC_API_KEY}}" },
  { key = "DEEPSEEK_API_KEY", value = "${{DEEPSEEK_API_KEY}}" },
  { key = "XAI_API_KEY", value = "${{XAI_API_KEY}}" },
  { key = "OPENROUTER_API_KEY", value = "${{OPENROUTER_API_KEY}}" }
]

# Database settings
[services.db]
name = "seo-agent-db"
type = "postgres"
plan = "standard"
envVars = [
  { key = "POSTGRES_URL", value = "${{Postgres.DATABASE_URL}}" },
]

# Enable metrics, alerts
[metrics]
enabled = true
