services:
  - type: web
    name: seo-agent-api
    env: python
    buildCommand: |
      echo "Python version:" && python --version
      echo "Installing packages..."
      pip install --no-cache-dir openai==0.28.1
      pip install --no-cache-dir -r requirements.txt
      echo "Installed packages:" && pip list
    startCommand: |
      echo "Starting FastAPI application..."
      echo "Current directory:" && pwd
      echo "Python path:" && echo $PYTHONPATH
      python -m uvicorn api.base:app --host 0.0.0.0 --port $PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /app
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: XAI_API_KEY
        sync: false
    healthCheckPath: /api/v1/health
    autoDeploy: true 